<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="LAPTOP-M4QTD56D" name="pytest" skipped="0" tests="9" time="0.100" timestamp="2021-01-12T16:12:19.887101"><testcase classname="test_calc.TestCalc" name="test_add" time="0.003" /><testcase classname="test_calc.TestCalc" name="test_add1" time="0.001" /><testcase classname="test_calc.TestCalc" name="test_add2" time="0.001" /><testcase classname="test_calc.TestCalc" name="test_add3" time="0.001" /><testcase classname="test_calc.TestCalc" name="test_div" time="0.001" /><testcase classname="test_calc.TestCalc" name="test_div2" time="0.001" /><testcase classname="test_demo" name="test_a" time="0.001" /><testcase classname="test_demo" name="test_b" time="0.001" /><testcase classname="test_demo" name="test_c" time="0.001"><failure message="assert 1 == 2">def test_c():
&gt;       assert 1 == 2
E       assert 1 == 2

test_demo.py:8: AssertionError</failure></testcase></testsuite></testsuites>